### ISSUE TITLE
[Feature request] Tools for annotating defect types

### ISSUE THREAD

**Issue by raunilillemets** [is-centre/datm-annotation-tool#1]
### Background information & goal
We need to add the possibility for defect type digitalization to the annotation tool. 

The digitizer must be able to choose the type of the defect when drawing new defects. To make this easier for the digitizer, the Tehnokeskus defect layer must be shown with certain specified colors (different colors for different defect types).

For already digitized defects, AI team will be apply certain GIS logic in order to match the defect types from the Tehnokeskus layer (which consists of point-, line-, and shape-objects) to the digitized layer (which consists only of shape-objects). These defect types will be coded into defect mask images (which use the same color as the annotation tool). The annotation tool must be able to read these images and let digitizer review and correct these masks (and apply missing types, if necessary).

### Specifications
**Existing Tehnokeskus defects must be shown with different styles** (styles and colors described below). List of possible Tehnokeskus defects:
- Servadefekt (SERV) = edge defect
- Auk (AUK) = pothole
- Murenemine (MUREN) = weathering
- Võrkpragu (VORK) = network cracking
- Paik (PAIK_J) = patched road (line)
- Paik (PAIK) = patched road (area)
- Kitsas/lai pikipragu (LPIKIPR, KPIKIPR) = Narrow/wide longitudinal crack 
- Põikpragu (POIKPR) = Transverse cracking
- Kitsas/lai vuugipragu (KVUUK, LVUUK) = Narrow/wide joint reflection crack

Narrow&wide versions of the same defects can be visualized in the same way.

For digitizing defect types, there must be two ways:
- Choose color of brush and draw with brush
- "Paint" existing defects (a la "paint" tool in MS Paint)

User must be able to choose brush color from the following types (differences with the Tehnokeskus defects are shown in bold):
- Servadefekt (SERV) = edge defect
- Auk (AUK) = pothole
- Murenemine (MUREN) = weathering
- Võrkpragu (VORK) = network cracking
- Paik (**PAIK**) = patched road (area)
- Pikipragu (**PIKIPR**) = longitudinal crack 
- Põikpragu (POIKPR) = Transverse cracking
- Vuugipragu (**VUUK**) = joint reflection crack
- Määramata (**UNDEF**) = undefined

In order to choose the brush color, user must be able to choose from a list where there is both the defect name (in English) and a visual sample of the defect style (for example, a small rectangle of that color).

Old images (with no defect types) must also be possible to be opened. Then all of the existing defects must be shown with "undefined" defect type.

### Color schemes (proposal)
See comment below.

**Comment by raunilillemets** [comment]
Specifications for defect types colors:
![defect types colors](https://user-images.githubusercontent.com/1147511/91959710-a368c200-ed11-11ea-9f29-75829f91b2ac.png)

Maybe the visual style for "auk" is not optimal - it might be hard to see the gray color on the asphalt. Then a new color should be chosen (or maybe white/yellow border should be added to the gray interior)

For Tehno polygon-objects, edge and the interior are of the same color, but fill should be 90% transparent. Digitized defects should have a dashed border line and the interior colors are brighter. 

Example of how these types look on a aerial photo background:
![sample](https://user-images.githubusercontent.com/1147511/91959714-a5328580-ed11-11ea-924a-f77334de3e74.png)

Important: these colors are just a suggestion. Feel free to make changes (but just document them here).

**Comment by extall** [comment]
OK, let me try to understand this better.

- You want the Tehnokeskus-drawn defects to be overlaid on top of the orthoframe and paint the defects in with different colors with the brush, correct?
- Should road area masking mode still be supported?

Please note that with this amount of changes it would be suboptimal to update the existing application with this new functionality directly. Rather, I will create a new development branch. So switching between branches you will be able to either use the old method, or the new one. Once the new branch reaches stable level, I can merge it into master branch, at which point there will be a single application.

I add this project to my to-do list, hopefully I can give you the first implementation for testing next week.

**Comment by raunilillemets** [comment]
Yes, Tehnokeskus-drawn defects should be overlaid on top of the orthoframe and the user-digitized defects should be drawn on top of that (with larger transparency, maybe?)

Yes, road area masking should still be supported.

**Comment by extall** [comment]
No, Tehnokeskus defects were either on or off and this must have been set in the menu. However, I can just add another layer in the drawable component to make it possible to draw them independently of the orthoframe. Then it should be possible to hide/show them easily.

**Comment by raunilillemets** [comment]
OK, very good.

**Comment by extall** [comment]
Done. Because the updated tool is backwards-compatible with old masks, I already merged it with master.
